#include "app/HelpDialog.hpp"

#include <QCoreApplication>
#include <QDialogButtonBox>
#include <QTextBrowser>
#include <QVBoxLayout>

namespace pictureviewer {

// ── Sdílený CSS styl pro všechny dialogy ─────────────────────────────────────
static const QString s_htmlStyle =
    "<style>"
    "body { font-family: -apple-system, 'Segoe UI', sans-serif; font-size: 13px;"
    "       color: #222; margin: 12px; }"
    "h2   { color: #1a5fa8; margin-bottom: 4px; }"
    "h3   { color: #444; margin-top: 14px; margin-bottom: 4px; }"
    "table{ border-collapse: collapse; width: 100%; }"
    "th   { background-color: #e8eef5; text-align: left; padding: 6px 10px;"
    "       font-weight: bold; }"
    "td   { padding: 5px 10px; border-bottom: 1px solid #ddd; }"
    "tr:last-child td { border-bottom: none; }"
    "ul   { margin: 4px 0; padding-left: 20px; }"
    "li   { margin-bottom: 4px; }"
    "kbd  { background: #f0f0f0; border: 1px solid #bbb; border-radius: 3px;"
    "       padding: 1px 5px; font-family: monospace; font-size: 12px; }"
    "p.note { color: #666; font-size: 12px; margin-top: 10px; }"
    "</style>";

// ── Konstruktor ───────────────────────────────────────────────────────────────
HelpDialog::HelpDialog(const QString &title, const QString &html, QWidget *parent)
    : QDialog(parent)
{
    setWindowTitle(title);
    setMinimumSize(540, 420);
    resize(580, 480);

    m_browser = new QTextBrowser(this);
    m_browser->setOpenExternalLinks(true);
    m_browser->setHtml(s_htmlStyle + html);

    auto *buttons = new QDialogButtonBox(QDialogButtonBox::Close, this);
    connect(buttons, &QDialogButtonBox::rejected, this, &QDialog::reject);

    auto *layout = new QVBoxLayout(this);
    layout->setContentsMargins(8, 8, 8, 8);
    layout->setSpacing(6);
    layout->addWidget(m_browser);
    layout->addWidget(buttons);
    setLayout(layout);
}

// ── O programu ────────────────────────────────────────────────────────────────
// Aktualizuj při přidání nových funkcí nebo změně popisu aplikace.
void HelpDialog::showAbout(QWidget *parent)
{
    const QString version = QCoreApplication::applicationVersion();
    const QString html = QString(
        "<h2>PictureViewer v.%1</h2>"
        "<p>Rychlý a přehledný prohlížeč obrázků pro <b>macOS</b> a <b>Windows</b>.</p>"
        "<h3>Funkce</h3>"
        "<ul>"
        "<li><b>Procházení souborů</b> — panel náhledů s obrázky a PDF dokumenty</li>"
        "<li><b>Podpora PDF</b> — PDF se zobrazují stejně jako obrázky s listováním stránek</li>"
        "<li><b>Slideshow</b> — automatická prezentace s volitelným intervalem"
        " (1, 2, 3, 5, 10, 20 nebo 30 sekund)</li>"
        "<li><b>Přiblížení/oddálení</b> — kolečkem myši nebo gesty trackpadu u obrázků i PDF</li>"
        "<li><b>Přizpůsobení oknu</b> — nebo zobrazení v originální velikosti (1:1)</li>"
        "<li><b>Zmenšit / zvětšit na okno</b> — dva přepínače vpravo dole ve status baru"
        " (⬇ a ⬆) určují, jak se obrázek zobrazí při načtení. Zapnuté zmenšení srazí"
        " velké obrázky do okna, zapnuté zvětšení roztáhne malé na velikost okna."
        " Vypnuté obojí zobrazí vše v originální velikosti (1:1). Ruční zoom kolečkem"
        " nebo <kbd>Mezerník</kbd> volbu dočasně přebijí — do načtení dalšího souboru."
        " Nastavení je per-profil a týká se jen statických obrázků, ne PDF a videa</li>"
        "<li><b>Plná obrazovka</b> — imerzivní režim pro prohlížení; jednotlivé toolbary"
        " lze připnout tlačítkem špendlíku na jejich pravém konci, aby zůstaly viditelné"
        " i ve fullscreenu</li>"
        "<li><b>Přejmenování souborů</b> — obrázků i PDF přímo z aplikace;"
        " zachová se i víceslovný název s tečkami (např. „dovolena.2024.01.jpg“"
        " se přejmenuje celý, ne jen část před první tečkou)</li>"
        "<li><b>Odstranění/přesunutí</b> — smazání nebo přesunutí do složky Delete."
        " Pokud disk nepodporuje koš (typicky síťové SMB sdílení), aplikace na to"
        " upozorní a nabídne trvalé smazání bez možnosti obnovy — nikdy ho neprovede"
        " sama bez potvrzení</li>"
        "<li><b>Smazat aktuální složku</b> — v hlavním toolbaru; smaže CELOU"
        " otevřenou složku i s obsahem do koše. Je-li prázdná (žádný soubor nikde"
        " v podstromu), smaže bez dotazu; jinak vypíše obsah a vyžádá potvrzení"
        " („Smazat včetně souborů“ / „Zrušit, nic nemazat“). Po smazání aplikace"
        " otevře následující sourozeneckou složku, jinak předchozí, jinak nadřazenou</li>"
        "<li><b>Přehrávání videa</b> — MP4, MKV, MOV, WebM a další formáty přímo v aplikaci;"
        " video se přehrává v nekonečné smyčce, dokud jej nezastavíte;"
        " zoom (+/-), posun myší, fullscreen (F), posun šipkami (±10 % délky),"
        " <kbd>Shift+←/→</kbd> přepíná na předchozí/další soubor; bez externích závislostí</li>"
        "<li><b>Profily</b> — oddělená nastavení, štítky a oblíbené složky pro více"
        " uživatelů či pracovních režimů; volba výchozího profilu při startu</li>"
        "<li><b>Automatické aktualizace</b> — Nápověda → Zkontrolovat aktualizace…"
        " najde nové vydání na GitHubu, ověří jeho integritu (SHA256) a na Windows"
        " je rovnou nainstaluje; tichá kontrola probíhá i po startu</li>"
        "<li><b>Metadata</b> — rozměry, velikost, formát, počet stránek (PDF)</li>"
        "<li><b>Zapamatování složky</b> — aplikace si pamatuje poslední otevřenou cestu</li>"
        "<li><b>Otevření z Finderu</b> — přímé otevření souborů z macOS/Windows</li>"
        "<li><b>Štítky obrázků</b> — přiřazení až 5 barevných štítků na obrázek; filtrování složky podle štítků; přejmenování, změna barvy a smazání štítku přes pravý klik</li>"
        "<li><b>Oblíbené složky</b> — toolbar s barevnými tlačítky pro rychlé přepínání mezi oblíbenými složkami (max 10); klik otevře složku, pravý klik odebere z oblíbených</li>"
        "<li><b>Přesun do složky</b> — vlastní tlačítka pro tematické roztřídění souborů;"
        " klik na tlačítko přesune aktuální (nebo více vybraných — Ctrl/Shift+klik v náhledech)"
        " obrázek, video či PDF do zvolené složky; při shodě jmen (i u párových souborů —"
        " viz níže) aplikace vypíše kolidující soubory a nabídne přejmenování celé skupiny"
        " najednou (nikdy nepřepíše); u dávkového přesunu více souborů lze zvolit „Zrušit“"
        " (jen aktuální soubor) nebo „Zrušit vše“ (celou frontu); tlačítko ↩ vrátí poslední"
        " přesuny zpět (LIFO), i s původními názvy před přejmenováním; tlačítka jsou"
        " per-profil a spravují se přes pravý klik (přejmenovat, změnit barvu, změnit složku, smazat)</li>"
        "<li><b>Navigace mezi složkami</b> — čtyři tlačítka pro rychlý pohyb v adresářové"
        " struktuře: ◀/▶ na abecedně předchozí/následující sourozeneckou složku, ▲ o úroveň"
        " výše, ▼ do první podsložky (abecedně); u každého tlačítka je vidět název cílové"
        " složky a počet složek v daném směru; interní složka „Delete“ je z navigace vyloučena;"
        " zjišťování adresářové struktury běží na pozadí a jen pokud je panel zapnutý</li>"
        "<li><b>Párové soubory (obrázek/video)</b> — volitelné v Nastavení (per-profil):"
        " při přesunu nebo smazání souboru aplikace najde ve stejné složce ostatní obrázky"
        " a videa se stejným názvem (např. „123.jpg“ + „123.mp4“) a přesune/smaže je také;"
        " PDF se nikdy nepáruje; při více nalezených párech se zeptá (vše / jen aktivní /"
        " storno); vrácení zpět (↩ i tlačítkem Vrátit poslední soubor) obnoví celou"
        " skupinu najednou</li>"
        "<li><b>Ořez obrázku</b> — tlačítko ořezu aktivuje výběr oblasti myší; zobrazení se"
        " ořízne na vybranou část; pravý klik → Kopírovat obrázek uloží výřez jako JPEG"
        " soubor do schránky</li>"
        "<li><b>Uložit / Uložit jako</b> — uložení upraveného obrázku (ořez, otočení) jako JPEG;"
        " Uložit nabídne přepsání originálu nebo uložení pod novým názvem;"
        " Uložit jako otevře dialog pro výběr názvu a cílové složky"
        " (originál nebo oblíbená složka). U videa se neupravuje nic, proto je"
        " Uložit vždy neaktivní; Uložit jako u videa uloží kopii souboru pod"
        " novým názvem (beze změny formátu). Otočení a ořez jsou u videa"
        " rovněž neaktivní</li>"
        "<li><b>Vrátit poslední soubor</b> — tlačítko vedle popelnic vrací soubory"
        " přesunuté do Delete zpět do původní složky (LIFO — nejnovější přesunutý"
        " jako první); aktivní jen pokud byl v&nbsp;tomto sezení přesunut alespoň"
        " jeden soubor</li>"
        "<li><b>PDF toolbar</b> — při otevření PDF se automaticky zobrazí lišta s tlačítky"
        " ◀&nbsp;/&nbsp;▶ pro listování, indikátorem aktuální strany, tlačítkem"
        " <i>Přejít na stranu</i> a tlačítkem <i>Screenshot</i> pro zachycení stránky"
        " jako obrázku (pak ji lze uložit přes Uložit jako)</li>"
        "<li><b>Obnovit složku</b> — první tlačítko toolbaru; znovu naskenuje aktuální"
        " složku a zobrazí nové nebo odebrané soubory; klávesová zkratka <kbd>F5</kbd></li>"
        "<li><b>Řazení v toolbaru</b> — dropdown tlačítko ukazuje aktivní řazení"
        " (např. Název ↑); kliknutím se volí klíč (název / datum / velikost) a směr</li>"
        "<li><b>Pamatování velikosti okna</b> — aplikace si pamatuje velikost a polohu okna;"
        " při změně monitoru (jiné rozlišení) se spustí v&nbsp;předvolené velikosti</li>"
        "<li><b>Přizpůsobitelná šířka panelu náhledů</b> — táhněte pravý okraj panelu"
        " náhledů doleva nebo doprava; miniatury se automaticky přizpůsobí šířce."
        " Nastavení se pamatuje mezi spuštěními</li>"
        "</ul>"
        "<p class='note'>Kompletní přehled ikon toolbaru s popisem najdete v"
        " Nápověda → Přehled tlačítek toolbaru.</p>"
        "<h3>Technologie</h3>"
        "<p>Napsáno v C++20 s frameworkem Qt&nbsp;6. "
        "Postaveno na macOS a Windows (GitHub Actions).</p>"
        "<p style='margin-top:16px; color:#888; font-size:12px;'>"
        "© 2025–2026 Jiří Krejčí</p>"
    ).arg(version);

    auto *dlg = new HelpDialog(tr("O programu"), html, parent);
    dlg->setAttribute(Qt::WA_DeleteOnClose);
    dlg->exec();
}

// ── Přehled tlačítek toolbaru ─────────────────────────────────────────────────
// Aktualizuj při přidání, odebrání nebo záměně ikony tlačítka v toolbaru.
void HelpDialog::showToolbarGuide(QWidget *parent)
{
    const QString html =
        "<h2>Přehled tlačítek toolbaru</h2>"
        "<p>Stejný text se zobrazí i jako tooltip po najetí myší na tlačítko v aplikaci.</p>"
        "<h3>Hlavní toolbar</h3>"
        "<table>"
        "<tr><th>Ikona</th><th>Tlačítko</th><th>Popis</th></tr>"
        "<tr><td><img src=':/icons/icon_open_folder.png' width='28' height='28'></td>"
        "    <td>Otevřít složku</td><td>Otevře dialog pro výběr složky s obrázky (Ctrl+O)</td></tr>"
        "<tr><td><img src=':/icons/icon_reload.png' width='28' height='28'></td>"
        "    <td>Znovu načíst složku</td><td>Znovu naskenuje aktuální složku a zobrazí přidané"
        " nebo odebrané soubory (F5)</td></tr>"
        "<tr><td><img src=':/icons/icon_screenshot.png' width='28' height='28'></td>"
        "    <td>Snímek obrazovky</td><td>Zachytí označenou oblast obrazovky (i mimo aplikaci)"
        " a otevře ji v prohlížeči</td></tr>"
        "<tr><td><img src=':/icons/icon_previous.png' width='28' height='28'></td>"
        "    <td>Předchozí obrázek</td><td>Přejde na předchozí soubor ve složce (Shift+←)</td></tr>"
        "<tr><td><img src=':/icons/icon_next.png' width='28' height='28'></td>"
        "    <td>Další obrázek</td><td>Přejde na následující soubor ve složce (Shift+→)</td></tr>"
        "<tr><td><img src=':/icons/icon_play_slideshow.png' width='28' height='28'></td>"
        "    <td>Spustit / zastavit slideshow</td><td>Spustí automatickou prezentaci; během"
        " přehrávání se ikona změní na tlačítko pro zastavení (S)</td></tr>"
        "<tr><td><img src=':/icons/icon_slideshow_interval.png' width='28' height='28'></td>"
        "    <td>Interval slideshow</td><td>Rozbalí nabídku pro volbu intervalu mezi snímky"
        " (1, 2, 3, 5, 10, 20 nebo 30 s)</td></tr>"
        "<tr><td><img src=':/icons/icon_sort.png' width='28' height='28'></td>"
        "    <td>Řazení souborů</td><td>Rozbalí nabídku pro volbu klíče řazení (název / datum"
        " změny / velikost) a směru (vzestupně / sestupně)</td></tr>"
        "<tr><td><img src=':/icons/icon_rename.png' width='28' height='28'></td>"
        "    <td>Přejmenovat obrázek</td><td>Otevře dialog pro zadání nového názvu"
        " aktuálního souboru (R)</td></tr>"
        "<tr><td><img src=':/icons/icon_rotate_left.png' width='28' height='28'></td>"
        "    <td>Otočit doleva</td><td>Otočí zobrazený obrázek o 90° doleva ([ nebo L)</td></tr>"
        "<tr><td><img src=':/icons/icon_rotate_right.png' width='28' height='28'></td>"
        "    <td>Otočit doprava</td><td>Otočí zobrazený obrázek o 90° doprava (]);"
        " u videa neaktivní</td></tr>"
        "<tr><td><img src=':/icons/icon_crop.png' width='28' height='28'></td>"
        "    <td>Ořez obrázku</td><td>Aktivuje výběr oblasti myší; zobrazení se ořízne na"
        " vybranou část; u videa neaktivní</td></tr>"
        "<tr><td><img src=':/icons/icon_save_overwrite.png' width='28' height='28'></td>"
        "    <td>Uložit</td><td>Uloží upravený obrázek (ořez, otočení) — nabídne přepsání"
        " originálu nebo uložení pod novým názvem; u videa neaktivní (nic se"
        " neupravuje)</td></tr>"
        "<tr><td><img src=':/icons/icon_save_as.png' width='28' height='28'></td>"
        "    <td>Uložit jako</td><td>Otevře dialog pro uložení pod novým názvem,"
        " s možností volby cílové složky; u obrázku uloží jako JPEG, u videa"
        " vytvoří kopii souboru beze změny formátu</td></tr>"
        "<tr><td><img src=':/icons/icon_delete_current.png' width='28' height='28'></td>"
        "    <td>Smazat obrázek</td><td>Odstraní aktuální obrázek (do koše, nebo přesune do"
        " složky Delete — podle nastavení) (D)</td></tr>"
        "<tr><td><img src=':/icons/icon_move_to_trash.png' width='28' height='28'></td>"
        "    <td>Smazání složky Delete</td><td>Smaže celou interní podsložku „Delete“"
        " i s obsahem do koše</td></tr>"
        "<tr><td><img src=':/icons/icon_delete_permanently.png' width='28' height='28'></td>"
        "    <td>Smazat aktuální složku</td><td>Smaže celou otevřenou složku i s obsahem do"
        " koše; prázdnou bez dotazu, jinak s potvrzením a seznamem obsahu</td></tr>"
        "<tr><td><img src=':/icons/icon_remove_from_trash.png' width='28' height='28'></td>"
        "    <td>Vrátit poslední soubor</td><td>Vrátí naposledy smazaný/přesunutý soubor zpět"
        " do původní složky</td></tr>"
        "</table>"
        "<h3>Zobrazit / skrýt postranní panely</h3>"
        "<table>"
        "<tr><th>Ikona</th><th>Tlačítko</th><th>Popis</th></tr>"
        "<tr><td><img src=':/icons/icon_favorites_folders.png' width='28' height='28'></td>"
        "    <td>Oblíbené složky</td><td>Zobrazí/skryje panel s rychlým přepínáním mezi"
        " oblíbenými složkami</td></tr>"
        "<tr><td><img src=':/icons/icon_tags.png' width='28' height='28'></td>"
        "    <td>Štítky</td><td>Zobrazí/skryje panel pro přiřazování a filtrování"
        " barevných štítků</td></tr>"
        "<tr><td><img src=':/icons/icon_move_folder.png' width='28' height='28'></td>"
        "    <td>Přesun do složky</td><td>Zobrazí/skryje panel s tlačítky pro tematické"
        " roztřídění souborů do vlastních cílových složek</td></tr>"
        "<tr><td><img src=':/icons/icon_navigation.png' width='28' height='28'></td>"
        "    <td>Navigace mezi složkami</td><td>Zobrazí/skryje panel pro rychlý pohyb"
        " v adresářové struktuře</td></tr>"
        "</table>"
        "<h3>Panel Oblíbené složky</h3>"
        "<p>➕ přidá aktuální složku mezi oblíbené (max 10). Barevná tlačítka jsou"
        " vytvořená uživatelem — klik otevře složku, pravý klik nabídne odebrání.</p>"
        "<h3>Panel Štítky</h3>"
        "<p>➕ vytvoří nový štítek. ❌ odebere všechny štítky z aktuálního obrázku."
        " ✕ zruší aktivní filtr podle štítků. Barevná tlačítka filtrují zobrazenou"
        " složku podle konkrétního štítku — pravý klik nabídne přejmenování, změnu"
        " barvy nebo smazání štítku.</p>"
        "<h3>Panel Přesun do složky</h3>"
        "<p>➕ vytvoří nové tlačítko přesunu (název, barva, cílová složka). ↩ vrátí"
        " poslední přesunuté soubory zpět (LIFO). Barevná tlačítka jsou vytvořená"
        " uživatelem — klik přesune aktuální (nebo vybrané) soubory do cílové"
        " složky, pravý klik nabídne správu tlačítka.</p>"
        "<h3>Panel Navigace mezi složkami</h3>"
        "<p>▲ o úroveň výše, ◀ / ▶ na abecedně předchozí/následující sourozeneckou"
        " složku, ▼ do první podsložky. Každé tlačítko zobrazuje název cílové"
        " složky a počet souborů v daném směru.</p>"
        "<h3>PDF toolbar</h3>"
        "<p>Zobrazí se automaticky při otevření PDF souboru. ◀ / ▶ listují stránky"
        " (PgUp/PgDn), indikátor uprostřed ukazuje aktuální stranu, <i>Přejít na"
        " stranu</i> otevře dialog pro přímý skok, <i>Screenshot</i> uloží aktuální"
        " stranu jako obrázek (lze pak uložit přes Uložit jako).</p>"
        "<h3>Připnutí panelu ve fullscreenu</h3>"
        "<p><img src=':/icons/pin_red.png' width='20' height='20'>&nbsp;/&nbsp;"
        "<img src=':/icons/pin_green.png' width='20' height='20'>"
        " — každý postranní toolbar má na svém pravém konci tlačítko špendlíku."
        " Aktivní (zelený) špendlík zajistí, že daný toolbar zůstane viditelný"
        " i v režimu celé obrazovky.</p>";

    auto *dlg = new HelpDialog(tr("Přehled tlačítek toolbaru"), html, parent);
    dlg->setAttribute(Qt::WA_DeleteOnClose);
    dlg->resize(640, 620);
    dlg->exec();
}

// ── Podporované formáty ───────────────────────────────────────────────────────
// Aktualizuj při přidání nebo odebrání formátu v ImageFormats.hpp.
void HelpDialog::showFormats(QWidget *parent)
{
    const QString html =
        "<h2>Podporované formáty</h2>"
        "<h3>Obrázky</h3>"
        "<table>"
        "<tr><th>Přípona</th><th>Formát</th><th>Poznámka</th></tr>"
        "<tr><td><kbd>.jpg</kbd>&nbsp;/&nbsp;<kbd>.jpeg</kbd></td>"
        "    <td>JPEG</td>"
        "    <td>Nejpoužívanější formát pro fotografie</td></tr>"
        "<tr><td><kbd>.png</kbd></td>"
        "    <td>PNG</td>"
        "    <td>Bezztrátová komprese, podpora průhlednosti</td></tr>"
        "<tr><td><kbd>.gif</kbd></td>"
        "    <td>GIF</td>"
        "    <td>Statické i animované obrázky</td></tr>"
        "<tr><td><kbd>.bmp</kbd></td>"
        "    <td>BMP</td>"
        "    <td>Bitmapový formát Windows</td></tr>"
        "<tr><td><kbd>.webp</kbd></td>"
        "    <td>WebP</td>"
        "    <td>Moderní webový formát (Google)</td></tr>"
        "<tr><td><kbd>.tiff</kbd>&nbsp;/&nbsp;<kbd>.tif</kbd></td>"
        "    <td>TIFF</td>"
        "    <td>Profesionální bezztrátový formát</td></tr>"
        "</table>"
        "<h3>Dokumenty</h3>"
        "<table>"
        "<tr><th>Přípona</th><th>Formát</th><th>Poznámka</th></tr>"
        "<tr><td><kbd>.pdf</kbd></td>"
        "    <td>PDF</td>"
        "    <td>Přenosný formát dokumentů (lze vypnout v nastavení)</td></tr>"
        "</table>"
        "<p class='note'>Filtr souborů ignoruje velikost písmen&nbsp;—"
        " <kbd>.JPG</kbd> i <kbd>.jpg</kbd> jsou rozpoznány shodně.</p>"
        "<p class='note'>Seznam obrázkových formátů se odvozuje z Qt pluginů"
        " nainstalovaných v systému, takže podle prostředí mohou být dostupné"
        " i&nbsp;<kbd>.heic</kbd>, <kbd>.heif</kbd>, <kbd>.svg</kbd>,"
        " <kbd>.jp2</kbd> a&nbsp;další.</p>";

    auto *dlg = new HelpDialog(tr("Podporované formáty"), html, parent);
    dlg->setAttribute(Qt::WA_DeleteOnClose);
    dlg->exec();
}

// ── Klávesové zkratky ─────────────────────────────────────────────────────────
// Aktualizuj při přidání nebo změně klávesových zkratek v MainWindow.cpp.
void HelpDialog::showShortcuts(QWidget *parent)
{
    const QString html =
        "<h2>Klávesové zkratky</h2>"
        "<h3>Navigace a zobrazení</h3>"
        "<table>"
        "<tr><th>Akce</th><th>Zkratka</th></tr>"
        "<tr><td>Otevřít složku</td>"
        "    <td><kbd>⌘ Shift O</kbd> (Mac) / <kbd>Ctrl+Shift+O</kbd> (Windows)</td></tr>"
        "<tr><td>Otevřít soubor</td>"
        "    <td><kbd>⌘ O</kbd> (Mac) / <kbd>Ctrl+O</kbd> (Windows)</td></tr>"
        "<tr><td>Předchozí obrázek</td>"
        "    <td><kbd>←</kbd> (šipka vlevo)</td></tr>"
        "<tr><td>Další obrázek</td>"
        "    <td><kbd>→</kbd> (šipka vpravo)</td></tr>"
        "<tr><td>První obrázek</td>"
        "    <td><kbd>↑</kbd> (šipka nahoru)</td></tr>"
        "<tr><td>Poslední obrázek</td>"
        "    <td><kbd>↓</kbd> (šipka dolů)</td></tr>"
        "<tr><td>Přizpůsobit oknu / původní velikost</td>"
        "    <td><kbd>Mezerník</kbd> nebo <kbd>Střed myši</kbd></td></tr>"
        "<tr><td>Přepnout panel náhledů</td>"
        "    <td><kbd>⌘ T</kbd> (Mac) / <kbd>Ctrl+T</kbd> (Windows)</td></tr>"
        "<tr><td>Předchozí stránka PDF</td>"
        "    <td><kbd>PgUp</kbd></td></tr>"
        "<tr><td>Následující stránka PDF</td>"
        "    <td><kbd>PgDn</kbd></td></tr>"
        "</table>"
        "<h3>Slideshow</h3>"
        "<table>"
        "<tr><th>Akce</th><th>Zkratka</th></tr>"
        "<tr><td>Spustit / zastavit slideshow</td>"
        "    <td><kbd>S</kbd></td></tr>"
        "</table>"
        "<h3>Přehrávač videa</h3>"
        "<p class='note'>Video se přehrává v nekonečné smyčce, dokud je nezastavíte"
        " (⏹, <kbd>Esc</kbd> nebo <kbd>↓</kbd>).</p>"
        "<table>"
        "<tr><th>Akce</th><th>Zkratka</th></tr>"
        "<tr><td>Spustit video</td>"
        "    <td><kbd>V</kbd></td></tr>"
        "<tr><td>Přehrát / pauza</td>"
        "    <td><kbd>Mezerník</kbd></td></tr>"
        "<tr><td>Posun vpřed o 10 % délky</td>"
        "    <td><kbd>→</kbd> (šipka vpravo)</td></tr>"
        "<tr><td>Posun zpět o 10 % délky</td>"
        "    <td><kbd>←</kbd> (šipka vlevo)</td></tr>"
        "<tr><td>Předchozí / další soubor</td>"
        "    <td><kbd>Shift+←</kbd> / <kbd>Shift+→</kbd></td></tr>"
        "<tr><td>Přesunout / smazat přehrávané video</td>"
        "    <td><kbd>D</kbd> nebo <kbd>Delete</kbd></td></tr>"
        "<tr><td>Přejmenovat přehrávané video</td>"
        "    <td><kbd>R</kbd></td></tr>"
        "<tr><td>Přejít na začátek</td>"
        "    <td><kbd>↑</kbd> (šipka nahoru)</td></tr>"
        "<tr><td>Zastavit přehrávání</td>"
        "    <td><kbd>↓</kbd> (šipka dolů) nebo <kbd>Esc</kbd></td></tr>"
        "<tr><td>Přiblížit</td>"
        "    <td><kbd>+</kbd> (první stisk +5 %, každý další +10 %)</td></tr>"
        "<tr><td>Oddálit (min. = velikost okna)</td>"
        "    <td><kbd>-</kbd> (první stisk -5 %, každý další -10 %)</td></tr>"
        "<tr><td>Posunout zvětšené video</td>"
        "    <td>Tažení myší</td></tr>"
        "<tr><td>Celá obrazovka / zpět</td>"
        "    <td><kbd>F</kbd></td></tr>"
        "</table>"
        "<h3>Složka</h3>"
        "<table>"
        "<tr><th>Akce</th><th>Zkratka</th></tr>"
        "<tr><td>Znovu načíst složku</td>"
        "    <td><kbd>F5</kbd></td></tr>"
        "</table>"
        "<h3>Úpravy a režimy</h3>"
        "<table>"
        "<tr><th>Akce</th><th>Zkratka</th></tr>"
        "<tr><td>Přejmenovat obrázek</td>"
        "    <td><kbd>R</kbd></td></tr>"
        "<tr><td>Otočit doleva / doprava</td>"
        "    <td><kbd>[</kbd> nebo <kbd>L</kbd> / <kbd>]</kbd></td></tr>"
        "<tr><td>Odstranit / přesunout obrázek</td>"
        "    <td><kbd>Delete</kbd>, <kbd>d</kbd>, <kbd>D</kbd></td></tr>"
        "<tr><td>Plná obrazovka</td>"
        "    <td><kbd>F</kbd></td></tr>"
        "<tr><td>Ukončit plnou obrazovku</td>"
        "    <td><kbd>Esc</kbd></td></tr>"
        "<tr><td>Ukončit aplikaci</td>"
        "    <td><kbd>⌘ Q</kbd> (Mac) / <kbd>Ctrl+Q</kbd> (Windows)</td></tr>"
        "</table>";

    auto *dlg = new HelpDialog(tr("Klávesové zkratky"), html, parent);
    dlg->setAttribute(Qt::WA_DeleteOnClose);
    dlg->exec();
}

// ── Co je nového ─────────────────────────────────────────────────────────────
// Aktualizuj při každém vydání nové verze.
void HelpDialog::showWhatsNew(QWidget *parent)
{
    const QString html =
        "<h2>Co je nového</h2>"
        "<h3>Verze 0.32</h3>"
        "<ul>"
        "<li><b>Oprava: aplikace nešla spustit (Windows)</b> — po aktualizaci"
        " na 0.31 se otevřelo prázdné okno, které se po pár sekundách samo"
        " zavřelo. Oprava v 0.31 byla neúplná: pád jen odsunula za zobrazení"
        " okna, takže se na macOS přestal projevovat, ale na Windows zůstal."
        " Nyní je odstraněna jeho skutečná příčina — přesouvání panelu PDF"
        " po obnovení uloženého rozložení oken</li>"
        "<li><b>Jednorázový reset rozložení panelů</b> — uložené rozložení"
        " z verzí 0.29–0.31 mohlo být poškozené, proto se při prvním spuštění"
        " zahodí. Šířka panelu náhledů se tím vrátí na výchozí; velikost"
        " a poloha okna zůstávají</li>"
        "</ul>"
        "<h3>Verze 0.31</h3>"
        "<ul>"
        "<li><b>Oprava: aplikace se nemusela vůbec spustit</b> — po zavření si"
        " za určitých okolností uložila rozložení oken, které ji při dalším"
        " startu shodilo. Aplikace pak nešla spustit, dokud se ručně nesmazalo"
        " uložené rozložení. Chyba se týkala verzí 0.29 a 0.30 a projevila se"
        " podle konkrétního rozmístění panelů, takže ne u každého. Příčinou"
        " bylo přesouvání PDF panelu do správného pořadí v nevhodný okamžik"
        " při startu</li>"
        "</ul>"
        "<h3>Verze 0.30</h3>"
        "<ul>"
        "<li><b>Aktualizace na sebe upozorní sama</b> — najde-li aplikace po"
        " spuštění novou verzi, zobrazí rovnou dialog s nabídkou stažení."
        " Dosud jen napsala hlášku do stavového řádku, kterou první přechod"
        " na jiný soubor přepsal, takže si jí šlo snadno nevšimnout."
        " Kontrola probíhá minutu po spuštění (dřív po pěti) a nejvýš"
        " jednou denně; „Máte nejnovější verzi“ ani chyba připojení"
        " neruší ničím. Verze označená „Přeskočit tuto verzi“ se"
        " automaticky nepřipomíná</li>"
        "<li><b>Oprava (Windows): aplikace se po aktualizaci znovu spustí</b>"
        " — dosud se po dokončení instalace neotevřela a bylo ji potřeba"
        " spustit ručně</li>"
        "<li><b>Přejmenování a párové soubory</b> — při zapnuté volbě"
        " „Přesouvat/mazat i párové soubory“ se přejmenuje celá dvojice"
        " (obrázek i jeho video), ne jen aktivní soubor. Dřív pár osiřel"
        " a přestal se párovat. Koliduje-li nový název u kteréhokoli souboru"
        " skupiny, nepřejmenuje se nic</li>"
        "<li><b>Uložit jako u videa</b> — vytvoří kopii videosouboru pod novým"
        " názvem (beze změny formátu). Tlačítko Uložit je u videa neaktivní,"
        " protože se ve videu nic neupravuje</li>"
        "<li><b>Otočení a ořez u videa</b> — tlačítka jsou nově neaktivní;"
        " dřív šla zmáčknout, ale neudělala nic</li>"
        "<li><b>Nová ikona přejmenování</b> a mírně širší tlačítka hlavního"
        " panelu</li>"
        "</ul>"
        "<h3>Verze 0.29</h3>"
        "<ul>"
        "<li><b>Nový vzhled toolbarů</b> — vlastní barevné ikony místo emoji"
        " u většiny tlačítek, menší a jednotná velikost, bez orámování"
        " a bez oddělovacích čar mezi skupinami</li>"
        "<li><b>Nová funkce: zmenšit / zvětšit na okno</b> — dva přepínače vpravo"
        " dole ve status baru určují, jak se obrázek zobrazí při načtení."
        " Vypnuté obojí zobrazí vše v originální velikosti (1:1). Ruční zoom"
        " volbu dočasně přebije. Nastavení je per-profil</li>"
        "<li><b>Interval slideshow tlačítkem</b> — místo číselníku rozbalovací"
        " nabídka (1, 2, 3, 5, 10, 20, 30 s) s větším tučným písmem;"
        " stejné písmo má i nabídka řazení</li>"
        "<li><b>Nová stránka nápovědy</b> — Nápověda → Přehled tlačítek toolbaru"
        " ukazuje ikonu, název a popis ke každému tlačítku</li>"
        "<li><b>Mazání na síťových discích</b> — disky bez podpory koše (typicky"
        " SMB sdílení) mazání dosud tiše odmítaly; aplikace teď nabídne trvalé"
        " smazání s potvrzením</li>"
        "<li><b>Oprava: pády při rychlém přepínání videí</b> — rychlé listování"
        " <kbd>Shift+←/→</kbd> mezi videosoubory shazovalo aplikaci. Přehrávač"
        " se nyní pro každý soubor vytváří znovu, což kolizi uvnitř systémové"
        " video vrstvy odstraňuje</li>"
        "<li><b>Oprava: náhledy videí se nezobrazovaly z cache</b> — po otevření"
        " složky se už uložené náhledy videí objeví ihned, i když se hned"
        " spustí přehrávání</li>"
        "<li><b>Oprava: přejmenování názvů s tečkami</b> — soubor jako"
        " „dovolena.2024.01.jpg“ přišel při přejmenování o část názvu</li>"
        "<li><b>Oprava: PDF toolbar</b> — zobrazoval se nad hlavním toolbarem;"
        " nyní je vždy úplně dole pod všemi ostatními</li>"
        "<li><b>Oprava: tlačítko Uložit jako</b> — po otevření obrázku zůstávalo"
        " neaktivní, dokud se neprovedla úprava</li>"
        "<li><b>Oprava: okno po fullscreenu a názvy profilů</b> — ošetřeny"
        " neplatné názvy profilů, které mohly poškodit uložené nastavení</li>"
        "<li><b>Vnitřní úklid</b> — sjednocený styl tlačítek toolbarů, odstraněné"
        " ladicí výpisy, úklid starých dočasných snímků obrazovky, 16 nových"
        " jednotkových testů (celkem 79)</li>"
        "</ul>"
        "<h3>Verze 0.28</h3>"
        "<ul>"
        "<li><b>Nová funkce: smazání aktuální složky (🚮)</b> — nové tlačítko"
        " v hlavním toolbaru smaže celou otevřenou složku i s obsahem do koše;"
        " prázdnou smaže rovnou, jinak vyžádá potvrzení se seznamem obsahu;"
        " po smazání otevře další/předchozí sourozeneckou složku, jinak nadřazenou</li>"
        "<li><b>Připnutí toolbarů pro fullscreen</b> — každý toolbar má nové"
        " tlačítko 📌; když je aktivní, toolbar zůstane viditelný i v režimu"
        " celé obrazovky (funkční štítky, přesun, přejmenování apod.)</li>"
        "<li><b>Oprava: přesun párových souborů</b> — obrázek a jeho video se"
        " stejným názvem se teď při kolizi jména v cílové složce přejmenují"
        " společně, jedním dialogem; u dávkového přesunu více souborů lze"
        " zvolit „Zrušit“ (jen aktuální) nebo „Zrušit vše“ (celou frontu)</li>"
        "<li><b>Oprava: pozice okna po fullscreenu</b> — okno se teď vrací"
        " přesně na stejnou pozici a velikost jako před vstupem do celé"
        " obrazovky</li>"
        "<li><b>Oprava: navigace mezi složkami na síťových discích</b> —"
        " tlačítka doleva/doprava/dolů na některých síťových discích"
        " (SMB/AFP) nefungovala, opraveno</li>"
        "</ul>"
        "<h3>Verze 0.27</h3>"
        "<ul>"
        "<li><b>Odolnější přehrávání videa</b> — při selhání načtení souboru"
        " (např. na pomalé síti) aplikace automaticky zkusí přehrávání znovu"
        " (až 3 pokusy), místo aby přehrávání rovnou skončilo chybou</li>"
        "<li><b>Plynulejší obraz videa</b> — zapnuta bilineární interpolace,"
        " hrany a čáry ve videu už nejsou zubaté</li>"
        "<li><b>Náhledy videí ze síťových disků</b> — prodloužen časový limit"
        " pro generování náhledu, takže se náhledy pomalých síťových videí"
        " už nevynechávají</li>"
        "<li><b>Oprava</b> — tlačítko „Delete folder“ se chybně zakazovalo"
        " i v prázdné složce</li>"
        "<li><b>Oprava</b> — tlačítko slideshow se během přehrávání elidovalo"
        " na „...“</li>"
        "</ul>"
        "<h3>Verze 0.26</h3>"
        "<ul>"
        "<li><b>Oprava pádu aplikace</b> — video náhledy mohly za určitých okolností"
        " (přesun/smazání souboru během generování náhledů) přistoupit k už uvolněné"
        " položce v panelu náhledů a shodit aplikaci. Vyřešeno bezpečnějším propojením"
        " náhledů s položkami seznamu, které se samo zneplatní při smazání řádku</li>"
        "<li><b>Interní úklid kódu</b> — sjednocení duplicitní logiky (barevná paleta,"
        " opakované pokusy o práci se soubory, řazení, vracení přesunů/mazání zpět)"
        " a odstranění zbytečné závislosti jádra aplikace na kategoriích</li>"
        "</ul>"
        "<h3>Verze 0.25</h3>"
        "<ul>"
        "<li><b>Nová funkce: párové soubory (obrázek/video)</b> — v Nastavení lze"
        " zapnout „Přesouvat/mazat i párové soubory“. Při přesunu (toolbar Přesun)"
        " nebo smazání souboru pak aplikace najde ve stejné složce ostatní obrázky"
        " a videa se stejným názvem (např. „123.jpg“ a „123.mp4“) a přesune/smaže"
        " je také. Volba je per-profil</li>"
        "<li><b>PDF se nikdy nepáruje</b> — párování se týká jen obrázků a videí</li>"
        "<li><b>Dialog při více párech</b> — najde-li se k souboru více souvisejících"
        " souborů, aplikace je vypíše a nechá zvolit: přesunout/smazat vše, jen"
        " aktivní soubor, nebo akci stornovat</li>"
        "<li><b>Skupinové vrácení zpět</b> — ↩ (Přesun) i ♻ (recyklace z Delete)"
        " vrátí celou skupinu (aktivní soubor + jeho páry) jedním krokem</li>"
        "</ul>"
        "<h3>Verze 0.24</h3>"
        "<ul>"
        "<li><b>Okamžité ukládání nastavení</b> — každá změna (toolbary, zpracování"
        " obrázků/videí/PDF, mazání, cache, řazení…) se teď zapíše na disk hned,"
        " ne až při zavření aplikace. Nastavení tak přežije i pád nebo vynucené"
        " ukončení aplikace</li>"
        "<li><b>Toolbary a nastavení jsou plně per-profil</b> — po přepnutí profilu"
        " se korektně obnoví viditelnost všech toolbarů (Oblíbené, Štítky, Přesun,"
        " Navigace) i zaškrtávací volby v menu Nastavení podle aktivního profilu;"
        " panel náhledů a navigační toolbar se navíc při přepnutí správně vyprázdní"
        " místo zobrazování starých dat z předchozího profilu</li>"
        "<li><b>Oprava: toolbary po fullscreenu</b> — dřív se po návratu z celé"
        " obrazovky (F) sekundární toolbary (Oblíbené/Štítky/Přesun/Navigace)"
        " nesprávně skryly; teď se vrátí přesně do stavu před vstupem do fullscreenu</li>"
        "<li><b>Pořadí/počet souborů u videa</b> — status lišta teď u přehrávaného"
        " videa zobrazuje pořadí a celkový počet souborů ve složce, stejně jako"
        " u obrázků a PDF</li>"
        "<li><b>Spolehlivější navigace mezi složkami</b> — kliknutí na tlačítko teď"
        " vždy nejdřív znovu ověří aktuální stav adresářové struktury, takže mezitím"
        " smazaná nebo přejmenovaná sousední složka už nezpůsobí chybu</li>"
        "<li><b>Oprava pádu aplikace</b> — rychlé přepínání voleb Zpracovávat"
        " obrázky/videa/PDF za sebou mohlo za určitých okolností shodit aplikaci"
        " kvůli asynchronnímu zpracování náhledů videí na pozadí. Generátor náhledů"
        " videí se teď při přerušení bezpečně restartuje místo pokračování se starým,"
        " potenciálně nekonzistentním stavem</li>"
        "</ul>"
        "<h3>Verze 0.23</h3>"
        "<ul>"
        "<li><b>Nová funkce: Navigace mezi složkami (🧭)</b> — samostatný toolbar se čtyřmi"
        " tlačítky pro rychlý pohyb v adresářové struktuře, aniž byste museli otevírat"
        " dialog Otevřít složku: ◀/▶ skočí na abecedně předchozí/následující sourozeneckou"
        " složku, ▲ o úroveň výše, ▼ do první podsložky (abecedně). Každé tlačítko ukazuje"
        " název cílové složky a počet složek v daném směru</li>"
        "<li><b>Interní složka „Delete“ je z navigace vyloučena</b> — slouží jen jako koš"
        " aplikace, nikdy se nenabídne jako cíl</li>"
        "<li><b>Zjišťování adresářové struktury na pozadí</b> — běží asynchronně a pouze"
        " pokud je panel navigace zapnutý, aby nezpomaloval procházení, když ho nepoužíváte</li>"
        "<li><b>Sjednocené velikosti ikon v hlavním toolbaru</b> — opravena nekonzistentní"
        " velikost ikon na macOS (tlačítko Přejmenovat, otočení, ořez a další nyní mají"
        " stejnou velikost jako Smazat obrázek / Smazat složku Delete)</li>"
        "</ul>"
        "<h3>Verze 0.22</h3>"
        "<ul>"
        "<li><b>Nová funkce: Přesun do složky (➡️)</b> — vlastní tlačítka pro tematické"
        " roztřídění velkého množství obrázků; každé tlačítko má název, barvu a cílovou"
        " složku (nastavuje se přes ➕ Nový). Klik na tlačítko přesune aktuální soubor,"
        " nebo hromadně více vybraných (Ctrl/Shift+klik v panelu náhledů)</li>"
        "<li><b>Ochrana proti přepsání</b> — pokud v cílové složce soubor stejného jména"
        " už existuje, aplikace zobrazí velikost a datum vytvoření obou souborů a nabídne"
        " přejmenování nebo zrušení přesunu; k přepsání nikdy nedojde</li>"
        "<li><b>Vrátit přesun zpět (↩)</b> — zásobník posledních přesunů (LIFO); opakovaným"
        " klikem lze vrátit více souborů za sebou, dokud nezavřete aplikaci</li>"
        "<li><b>Výběr více souborů v náhledech</b> — Ctrl/Shift+klik pro hromadné operace</li>"
        "<li><b>Oprava rozházeného toolbaru</b> — po přidání nového toolbaru Přesun se"
        " starý uložený layout oken dostal do konfliktu s novou strukturou a rozhazoval"
        " pořadí tlačítek a skrýval toolbary štítků/oblíbených; aplikace nyní starý"
        " neplatný layout při aktualizaci automaticky zahodí</li>"
        "</ul>"
        "<h3>Verze 0.21</h3>"
        "<ul>"
        "<li><b>Redesign toolbaru — jen ikony</b> — všechny tlačítka v hlavním,"
        " oblíbených a štítků toolbaru se nyní zobrazují jednotně bez textu;"
        " všechny ikony jsou velké 28×28 px pro konzistentní vzhled."
        " Text naleznete v tooltip (najetí myší)</li>"
        "</ul>"
        "<h3>Verze 0.20</h3>"
        "<ul>"
        "<li><b>Redesign toolbaru — jen ikony</b> — všechny tlačítka v hlavním,"
        " oblíbených a štítků toolbaru se nyní zobrazují jednotně bez textu;"
        " všechny ikony jsou velké 28×28 px pro konzistentní vzhled."
        " Text naleznete v tooltip (najetí myší)</li>"
        "<li><b>Ultramodernní design</b> — ikonový toolbar vychází z nejnovějších trendů"
        " (VS Code, Figma); šetrný prostor v okně, přesto plně funkční</li>"
        "<li><b>Lepší orientace ikonami</b> — zkušení uživatelé se ikony naučí za pár minut;"
        " tooltip vždy ukáže, co ikona znamená a jaká je přidělená klávesová zkratka</li>"
        "<li><b>Oprava přesunu videa do Delete</b> — prodloužen timeout pro uvolnění"
        " file handle z 600ms na 2 sekundy + detailní diagnostická hlášení"
        " (soubor zamčený, cíl existuje, chybí práva, apod.)</li>"
        "</ul>"
        "<h3>Verze 0.19</h3>"
        "<ul>"
        "<li><b>Oprava přesunu videa do Delete na Windows</b> — generátor náhledů"
        " držel poslední video otevřené a soubor tak zůstával zamčený; navíc se"
        " operace přesunu/smazání nyní v případě zamčeného souboru krátce opakuje</li>"
        "<li><b>Štítky přežijí přejmenování a přesun</b> — dříve se při přejmenování"
        " souboru štítky ztratily; nyní následují soubor (včetně vrácení z Delete)</li>"
        "<li><b>Hlášení poškozených videí</b> — nepřehratelné video zobrazí zprávu"
        " ve status baru místo tichého selhání</li>"
        "<li><b>Přejmenování přehrávaného videa</b> — funguje i během přehrávání;"
        " video se po přejmenování automaticky spustí znovu</li>"
        "<li><b>Otevřít soubor</b> — dialog nyní nabízí i videa a PDF</li>"
        "<li><b>Stabilita</b> — opraveny pády po přepnutí profilu (hlasitost videa,"
        " skenování složky); úklid databáze štítků; bezpečnější stahování aktualizací"
        " (streamování na disk, limit velikosti) a ochrana proti obřím obrázkům</li>"
        "</ul>"
        "<h3>Verze 0.18</h3>"
        "<ul>"
        "<li><b>Oprava mazání videa při přehrávání</b> — video se před přesunem"
        " do Delete nejdřív zastaví, aby soubor nebyl na Windows zamčený</li>"
        "</ul>"
        "<h3>Verze 0.17</h3>"
        "<ul>"
        "<li><b>Nekonečná smyčka videa</b> — video se přehrává stále dokola,"
        " dokud je uživatel sám nezastaví (⏹, Esc, ↓)</li>"
        "</ul>"
        "<h3>Verze 0.16</h3>"
        "<ul>"
        "<li><b>Automatické aktualizace</b> — Nápověda → Zkontrolovat aktualizace…"
        " zjistí nové vydání na GitHubu, stáhne instalátor, ověří SHA256 a na Windows"
        " jej rovnou nainstaluje; tichá kontrola i po startu (interval v config.ini)</li>"
        "<li><b>Nové chování šipek u videa</b> — <kbd>←/→</kbd> posouvá o ±10 %"
        " v přehrávaném videu, <kbd>Shift+←/→</kbd> přepíná mezi soubory</li>"
        "<li><b>Volba profilu při startu</b> — pamatovat poslední, nebo vždy začít"
        " zvoleným profilem</li>"
        "<li><b>Ochrana proti poškozeným videím</b> — 15s timeout načítání;"
        " zaseknuté video aplikaci neshodí</li>"
        "<li><b>Windows instalátor</b> — vydání obsahuje Inno Setup instalátor"
        " s SHA256 kontrolním souborem</li>"
        "</ul>"
        "<h3>Verze 0.15</h3>"
        "<ul>"
        "<li><b>Inline přehrávač videa</b> — video se přehrává přímo v okně aplikace"
        " (Qt Multimedia / AVFoundation / Media Foundation); VLC již není potřeba</li>"
        "<li><b>Zoom videa</b> — <kbd>+</kbd> zvětší obraz (první stisk +5 %, každý další +10 %);"
        " <kbd>-</kbd> zmenší, ale minimem je vždy velikost okna (video nikdy nezmenší pod okno)</li>"
        "<li><b>Posun zvětšeného videa myší</b> — po přiblížení lze obraz táhnout myší</li>"
        "<li><b>Klávesové zkratky přehrávače</b> — šipky pro vyhledávání (±10 % délky),"
        " začátek, zastavení; <kbd>F</kbd> přepíná fullscreen; <kbd>Mezerník</kbd> pauza</li>"
        "<li><b>Hlasitost</b> — posuvník v ovládací liště; hodnota se ukládá do config.ini"
        " a obnoví se při příštím spuštění</li>"
        "<li><b>Buffer overlay</b> — vizuální indikátor načítání při přehrávání ze síťových disků</li>"
        "<li><b>Metadata videa ve status baru</b> — název, velikost (MB), rozlišení,"
        " délka a vypočítaný datový tok (Mbit/s)</li>"
        "<li><b>Přepínání profilů</b> — opravena chyba kdy se obrázky nenačetly po přepnutí profilu</li>"
        "</ul>"
        "<h3>Verze 0.14</h3>"
        "<ul>"
        "<li><b>Snímek výřezu obrazovky (📷)</b> — nové tlačítko v hlavním toolbaru;"
        " funguje i mimo aplikaci a napříč všemi monitory. Označte oblast myší"
        " (Esc zruší) a výřez se otevře přímo v aplikaci. Dočasně se uloží do"
        " systémové temp složky — pro trvalé uložení použijte Uložit jako</li>"
        "<li><b>Přizpůsobitelná šířka panelu náhledů</b> — táhněte pravý okraj panelu"
        " náhledů (dělicí čáru) doleva nebo doprava; miniatury se automaticky zvětší"
        " nebo zmenší. Šířka se pamatuje mezi spuštěními</li>"
        "</ul>"
        "<h3>Verze 0.13</h3>"
        "<ul>"
        "<li><b>PDF toolbar na vlastním řádku</b> — PDF lišta se nyní zobrazuje pod toolbarem"
        " štítků a nikdy ji nepřekryje; oba toolbary mohou být aktivní současně</li>"
        "<li><b>Jednotná výška a písmo toolbarů</b> — všechny lišty (Oblíbené, Štítky, PDF)"
        " mají stejnou výšku a font jako hlavní toolbar (14 px tučné, výška 30 px)</li>"
        "<li><b>Oprava klávesy Mezerník v panelu náhledů</b> — zoom reset (Mezerník / 0)"
        " nyní funguje spolehlivě i&nbsp;při aktivním panelu náhledů; panel si klávesy neponechává</li>"
        "</ul>"
        "<h3>Verze 0.12</h3>"
        "<ul>"
        "<li><b>Obnovit složku (🔄 / F5)</b> — nové tlačítko na začátku toolbaru;"
        " znovu naskenuje aktuální složku a zobrazí přidané nebo odebrané soubory</li>"
        "<li><b>Řazení přesunuto do toolbaru</b> — dropdown tlačítko ukazuje aktivní"
        " stav (např. Název ↑); ze Settings menu bylo odebráno</li>"
        "</ul>"
        "<h3>Verze 0.11</h3>"
        "<ul>"
        "<li><b>PDF toolbar</b> — při zobrazení PDF se automaticky objeví lišta;"
        " tlačítka ◀&nbsp;/&nbsp;▶ listují stránky (stejné jako PgUp/PgDn);"
        " indikátor zobrazuje aktuální stranu a celkový počet</li>"
        "<li><b>Přejít na stranu</b> — dialog pro zadání čísla stránky (1&nbsp;–&nbsp;N),"
        " okamžitý skok na zvolenou stranu</li>"
        "<li><b>Screenshot PDF stránky</b> — tlačítko Screenshot zachytí aktuálně"
        " zobrazenou stránku jako statický obrázek; aktivují se tlačítka Uložit / Uložit jako"
        " a stránku lze uložit jako JPEG</li>"
        "</ul>"
        "<h3>Verze 0.10</h3>"
        "<ul>"
        "<li><b>Recyklace (♻)</b> — třetí tlačítko u popelnic vrací soubory přesunuté do Delete"
        " zpět do původní složky, v&nbsp;obráceném pořadí (nejnovější přesunutý jako první);"
        " po obnovení se aplikace přepne na obnovenou složku a soubor;"
        " tlačítko se deaktivuje, pokud nejsou žádné přesunuté soubory ke vrácení</li>"
        "</ul>"
        "<h3>Verze 0.9</h3>"
        "<ul>"
        "<li><b>Uložit</b> — po ořezu nebo otočení obrázku se aktivuje tlačítko Uložit;"
        " aplikace se zeptá, zda přepsat originál, nebo uložit pod novým názvem</li>"
        "<li><b>Uložit jako</b> — kdykoli dostupné pro statické obrázky; dialog pro zadání"
        " názvu souboru a výběr cílové složky (originál nebo oblíbená složka);"
        " soubor se vždy uloží jako JPEG</li>"
        "<li><b>Po uložení pod novým názvem</b> se aplikace automaticky přepne na nově uložený soubor</li>"
        "<li><b>Pamatování velikosti okna</b> — aplikace si pamatuje velikost a polohu okna"
        " při zavření; při jiném rozlišení obrazovky (jiný monitor) se spustí v předvolené velikosti</li>"
        "</ul>"
        "<h3>Verze 0.8</h3>"
        "<ul>"
        "<li><b>Systém štítků</b> — každému obrázku lze přiřadit až 5 barevných štítků"
        " přes tlačítka v toolbaru; přiřazení se uchovává v SQLite databázi vedle nastavení</li>"
        "<li><b>Filtrování složky podle štítků</b> — filtr toolbar zobrazuje jen štítky"
        " skutečně přiřazené obrázkům v aktuální složce; filtr se načítá líně (jen když je viditelný)</li>"
        "<li><b>Správa štítků přes pravý klik</b> — kliknutí pravým tlačítkem na libovolný"
        " štítek zobrazí menu s možnostmi Přejmenovat, Změnit barvu, Odstranit</li>"
        "<li><b>Oblíbené složky</b> — rychlý přístup k naposledy používaným složkám v menu Soubor</li>"
        "<li><b>Oprava výběru barvy</b> — při vytvoření nového štítku bez zvolené barvy se nyní"
        " skutečně vybere náhodná barva z dosud nepoužitých (dříve vždy první barva)</li>"
        "<li><b>Toolbar oblíbených složek</b> — tlačítko ⭐ Oblíbené zobrazí/skryje lištu"
        " s barevnými tlačítky složek; klik otevře složku, pravý klik ji odebere;"
        " [+ Přidat] přidá aktuální složku (max 10, při překročení limitu zobrazí varování)</li>"
        "<li><b>Ořez obrázku</b> — tlačítko ✂ v toolbaru aktivuje výběr oblasti; po označení"
        " se zobrazení ořízne; Kopírovat obrázek uloží výřez jako dočasný JPEG soubor do schránky"
        " (lze vložit do mailu, dokumentu nebo webové aplikace jako JPEG);"
        " ESC nebo pravý klik zruší výběr bez ořezu</li>"
        "</ul>"
        "<h3>Verze 0.7</h3>"
        "<ul>"
        "<li><b>Animované GIFy</b> — přehrávají se přes QMovie (dříve jen první snímek)</li>"
        "<li><b>Volba řazení</b> — Nastavení → Řazení souborů: podle názvu, data"
        " změny nebo velikosti, vzestupně i sestupně</li>"
        "<li><b>Indikátor zoomu</b> — aktuální zvětšení (%) vpravo ve status baru"
        " (u obrázků; 100&nbsp;% = originální velikost)</li>"
        "<li><b>Otočení obrázku</b> — klávesy <kbd>[</kbd>/<kbd>L</kbd> doleva,"
        " <kbd>]</kbd> doprava</li>"
        "<li><b>Drag &amp; drop</b> — přetažení složky nebo souboru přímo do okna</li>"
        "<li><b>Kontextové menu</b> — pravým tlačítkem: Zobrazit ve Finderu,"
        " kopírovat obrázek nebo cestu</li>"
        "<li><b>Více formátů</b> — seznam podporovaných obrázků se odvozuje"
        " z nainstalovaných Qt pluginů (HEIC, HEIF, SVG, JP2…)</li>"
        "<li>Jednotkové testy jádra (řazení, formáty, cache) proti regresím</li>"
        "</ul>"
        "<h3>Verze 0.6</h3>"
        "<ul>"
        "<li><b>Přepínatelná rozložení UI</b> — Klasický, Filmový pás, Imerzivní, "
        "Galerie a Pro režim (volba se pamatuje)</li>"
        "<li><b>Disková cache náhledů</b> — rychlejší opětovné načítání složek; "
        "automatický úklid při 500&nbsp;MB, zobrazení velikosti v nastavení</li>"
        "<li><b>Směrový prefetch</b> — při listování se přednačítá 5 souborů vpřed</li>"
        "<li><b>Přirozené řazení</b> — <kbd>img2</kbd> se řadí před <kbd>img10</kbd></li>"
        "<li><b>Vycentrované náhledy</b> — miniatury na výšku i PDF se vejdou do buňky</li>"
        "<li>Řada oprav stability — odstranění race conditions při načítání, "
        "mazání a přehrávání videa</li>"
        "</ul>"
        "<h3>Verze 0.5</h3>"
        "<ul>"
        "<li><b>Podpora PDF souborů</b> — PDF se zobrazují jako obrázky vedle ostatních souborů</li>"
        "<li><b>Stránkování PDF</b> — <kbd>PgDn</kbd> a <kbd>PgUp</kbd> pro listování mezi stránkami</li>"
        "<li><b>Náhledy PDF</b> — první stránka se generuje jako miniatura v panelu</li>"
        "<li><b>Nastavení PDF</b> — lze vypnout zpracování PDF souborů v nastaveních</li>"
        "<li><b>Status bar</b> — zobrazuje počet stránek u PDF souborů</li>"
        "<li>Stejné funkce pro PDF jako pro obrázky (zoom, delete, move to Delete folder)</li>"
        "</ul>"
        "<h3>Verze 0.4</h3>"
        "<ul>"
        "<li><b>Přehrávání videa</b> — podpora MP4, MOV, WebM a dalších formátů přes VLC</li>"
        "<li><b>Přejmenování obrázků</b> — nové tlačítko v liště a klávesová zkratka (R)</li>"
        "<li><b>Oprava spouštění</b> — aplikace se nyní spouští v jedné instanci při otevření souboru z Finderu</li>"
        "<li>Vyčištěn legacy Python kód — přechod na čistě C++ projekt</li>"
        "<li>Vylepšení VLC integrace — opravy chybějících klávesových zkratek a padajících procesů</li>"
        "</ul>"
        "<h3>Verze 0.3</h3>"
        "<ul>"
        "<li><b>Tlačítko přejmenování</b> — s ikonou v nástrojové liště</li>"
        "<li>Oprava při otevření obrázku z Finderu bez běžící aplikace</li>"
        "<li>Vylepšená detekce spouštěcího stavu aplikace</li>"
        "</ul>"
        "<h3>Verze 0.2</h3>"
        "<ul>"
        "<li>Sestava pro <b>Windows</b> — automatické sestavení přes GitHub Actions</li>"
        "<li>Oprava: panel náhledů se správně obnoví po opuštění celé obrazovky</li>"
        "<li>Menu Nápověda s přehledem funkcí, formátů, zkratek a changelogu</li>"
        "<li>Funkce pro mazání a přesunutí obrázků</li>"
        "</ul>"
        "<h3>Verze 0.1</h3>"
        "<ul>"
        "<li>Počáteční verze pro macOS</li>"
        "<li>Panel náhledů s rychlým načítáním ve vlákně na pozadí</li>"
        "<li>Slideshow s nastavitelným intervalem</li>"
        "<li>Přiblížení kolečkem myši / gesty trackpadu</li>"
        "<li>Režim celé obrazovky</li>"
        "<li>Zapamatování poslední otevřené složky</li>"
        "<li>Otevření souboru přímo z Finderu</li>"
        "</ul>";

    auto *dlg = new HelpDialog(tr("Co je nového"), html, parent);
    dlg->setAttribute(Qt::WA_DeleteOnClose);
    dlg->exec();
}

} // namespace pictureviewer
